config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  resources :stories  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  validates :title, presence: true

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

rescue_from(ActiveRecord::RecordNotFound, with: :record_not_found)

  private
  def record_not_found
    render(
      { file: "#{Rails.root}/public/404.html",
        status: :not_found,
        layout: false
      }
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_story, only: [:edit, :update, :destroy]

  def index
    @stories = current_user.stories.order(created_at: :desc)
  end

  def new
    @story = current_user.stories.new
  end
  
  def create
    @story = current_user.stories.new(story_params)
    @story.status = 'pulished' if params[:publish]
    if @story.save
      if params[:publish]
        redirect_to stories_path, notice: '故事發布成功'
      else
        redirect_to edit_storㄗ_path(@story), notice: '故事已儲存'
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @story.update(story_params)
      redirect_to stories_path, notice: '故事已更新'
    else
      render :edit
    end
  end

  def destroy
    @story.destroy
    redirect_to stories_path, notice: '故事已刪除'
  end
  private
  def find_story
    @story = current_user.stories.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/frontend/navbar' %>
    <%= render 'shared/frontend/flash' if notice %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/frontend/_flash.html.erb
<div class="notification is-primary">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= current_user.email %>
            </a>
    
            <div class="navbar-dropdown">
              <%= link_to "個人資料" , edit_user_registration_path , class: 'navbar-item' %>
              <%= link_to "新增故事" , new_story_path, class: 'navbar-item' %>
              <%= link_to "故事列表" , stories_path, class: 'navbar-item' %>
              <hr class="navbar-divider">
              <%= link_to "登出" , destroy_user_session_path , class: 'navbar-item' , method: 'delete' %>
            </div>
          </div>
          <% else %>
            <%= link_to "註冊" , new_user_registration_path , class: 'button is-primary'%>
            <%= link_to "登入" , new_user_session_path , class: 'button is-light'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/stories/_form.html.erb
<%= form_for(story) do |f| %>
  <div class="field">
    <%= f.label :title, '標題' %>
    <%= f.text_field :title, class: 'input is-primary is-medium' %>
  </div>
  <div class="field">
    <%= f.label :content, '內容' %>
    <%= f.text_area :content, class: 'textarea is-primary is-medium' %>
  </div>
  <div class="field">
    <%= f.submit '儲存草稿', name='save_as_draft', class: 'button is-medium' %>
    <%= f.submit '發布文章', name='publish', class: 'button is-medium is-primary' %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1 class="title">編輯故事</h1>

<%= render 'form', story: @story %>

app/views/stories/index.html.erb
<h1 class="title">故事列表</h1>


<% @stories.each do |story| %>
  <h2 class="title"><%= story.title %></h2>
  <div class="content">
    <p><%= story.content %></p>
    <p>最後編輯時間 <%= time_ago_in_words(story.updated_at) %>
      <%= link_to "編輯", edit_story_path(story), class: 'button is-text is-small' %>
      <%= link_to "刪除", story, class: 'button is-danger is-small', method: 'delete' %>
    </p>
  </div>
  <hr>
<% end %>

app/views/stories/new.html.erb
<h1 class="title">新增故事</h1>

<%= render 'form', story: @story %>